config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :picture
  validates :title, presence: true, length: { maximum: 15 }
  validates :memo, length: { maximum: 1000 }
  validate :image_presence

  def latitude
    if picture.attached?
      picture.metadata["latitude"]
    end
  end
  
  def longitude
    if picture.attached?
      picture.metadata["longitude"]
    end
  end

  def image_presence
    if picture.attached?
      if !picture.content_type.in?(%('image/jpeg image/png'))
        errors.add(:picture, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      errors.add(:picture, 'ファイルを添付してください')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        sleep 1
        format.html { redirect_to @picture, notice: "Picture was successfully created.", turbolinks: "false" }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:latitude, :longitude, :memo, :title, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
    <script type="text/javascript" src="https://rawgit.com/jieter/Leaflet.encoded/master/Polyline.encoded.js"></script>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <div class="card">
      <div class="card-body">
        <%= form_with(model: picture, local: true) do |form| %>
          <% if picture.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
        
              <ul>
                <% picture.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= form.label :picture %>
            <div class="custom-file">
              <%= form.file_field :picture, class: 'custom-file-input' %>
              <%= form.label :picture, class: "custom-file-label" %>
            </div>
          </div>
        
          <div class="form-group">
            <%= form.label :memo %>
            <%= form.text_area :memo, rows: 5, class: 'form-control' %>
          </div>
        
          <div class="form-group mt-4">
            <%= form.submit class: 'btn btn-success btn-block' %>
          </div>
          
        <% end %>
          
        <% if params[:action] == "edit" %>
          <div class="form-group mt-4">
            <%= link_to 'Show', @picture, class: 'btn btn-info btn-block' %>
          </div>
        <% end %>
        
        <div class="form-group mt-4">
          <%= link_to 'Back', pictures_path, class: 'btn btn-secondary btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="text-center my-4">
  <h1>Edit Picture</h1>
</div>

<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.title %></td>
      <td><%= picture.latitude %></td>
      <td><%= picture.longitude %></td>
      <td>
        <% if picture.picture.attached? %>
          <%= image_tag picture.picture.variant(resize: "50x50") %>
        <% end %>
      </td>
        <td><%= link_to 'Show', picture, class: "btn btn-sm btn-outline-info" %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture), class: "btn btn-sm btn-outline-success" %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path, class: "btn btn-success" %>

app/views/pictures/new.html.erb
<div class="text-center">
  <h1>New Picture</h1>
</div>

<%= render 'form', picture: @picture %>

<% content_for :back do %>
  <%= link_to 'Back', pictures_path %>
<% end %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Picture</h1>

<table class="table table-borderd">
  <div class="tbody">
    <tr>
      <th>Title</th>
      <td><%= @picture.title %></td>
    </tr>
    <tr>
      <th>Latitude</th>
      <td><%= @picture.latitude %></td>
    </tr>
    <tr>
      <th>Longitude</th>
      <td><%= @picture.longitude %></td>
    </tr>
    <tr>
      <th>Memo</th>
      <td><%= @picture.memo %></td>
    </tr>
    <tr>
      <th>Picture</th>
      <td>
        <% if @picture.picture.attached? %>
          <%= image_tag @picture.picture.variant(resize: "300x300") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Map</th>
      <td><div id="map" style="width: 100%; height: 500px;"></div></td>
    </tr>
  </div>
</table>

<%= link_to 'Edit', edit_picture_path(@picture), class: "btn btn-sm btn-success" %>
<%= link_to 'Back', pictures_path, class: "btn btn-sm btn-secondary" %>

<script>
    var map = L.map('map').setView([<%= @picture.latitude %>, <%= @picture.longitude %>], 13);
    L.tileLayer(
        'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
        }).addTo(map);
    L.marker(
        [<%= @picture.latitude %>, <%= @picture.longitude %>],
        {title: "marker-title"}
    ).addTo(map)
        .bindPopup("<%= @picture.title %>")
        .openPopup();
</script>